### PR TITLE
Route-based code splitting

### PR DESCRIPTION
**Pull request by ef4**

### CODE REVIEW

**Comment by ef4** [comment]
This is now deployed on https://beta.emberobserver.com/

**Comment by yohanmishkin** [comment]
👏 👏 👏

**Comment by ef4** [comment]
(The Percy failure seems to be several date fields that vary, it's not a real failure, the test suites is happy.)

**Comment by kategengler** [comment]
https://github.com/emberobserver/client/issues/146 will address Percy, eventually

**Pull request merged**
