### PR TITLE
Fix template linting error

### PR DESCRIPTION
**Pull request by balinterdi**
See https://travis-ci.org/emberjs/data/jobs/429955683

### CODE REVIEW

**Comment by kategengler** [comment]
Sorry about that!

**Comment by balinterdi** [comment]
No worries, and thank you for the insanely quick merge. And for EmberObserver! :)

**Comment by kategengler** [comment]
PRs show up in my Slack :) 

I didn't even realize template-lint generates tests like other lints. I wouldn't mind turning that off, if possible, and only running it via CLI in CI, so ember-data can just run tests and not worry about lints.

**Comment by balinterdi** [comment]
Right, I think that would make sense but I'm not sure if there's an option to do that. I think Ember CLI 3.4 added template lint tests and I've been fixing template errors in the projects I've upgraded (but luckily rather small ones).

**Comment by runspired** [comment]
Thanks all! Was about to come PR this myself :)

**Pull request merged**
