### PR TITLE
Add TrackJS badge to footer for error reporting

### PR DESCRIPTION
**Pull request by lisaychuang**
Reference issue #155 , add TrackJS badge to application.hbs footer section.

### CODE REVIEW

**Comment by lisaychuang** [comment]
Looks like CircleCI tests were failing because of linting?

**Comment by kategengler** [comment]
Yes, it looks like it is failing due to template-lint.

**Comment by lisaychuang** [comment]
@kategengler  happy to do so! I followed the Readme which still is still using `npm install` etc.  Suggest to update readme :)

**Comment by kategengler** [comment]
Ah, sorry about that! I think the README is a casualty of an Ember upgrade.

**Comment by lisaychuang** [comment]
Removed `package-lock.json` file

**Comment by kategengler** [comment]
Thanks again!!

**Pull request merged**
