### PR TITLE
[WIP] SVG icons

### PR DESCRIPTION
**Pull request by kaermorchen**
Hello.

What about change current font icons to svg icons? In this PR I replaced the icons in one place for example. 

For icons I used [ember-mdi](https://github.com/kaermorchen/ember-mdi) ([demo](https://kaermorchen.github.io/ember-mdi/)) which based on [materialdesignicons](https://materialdesignicons.com/)

Is it a good idea?

### CODE REVIEW

**Comment by kategengler** [comment]
I think switching to SVG icons is a good idea, but would prefer to keep the current icons. Using https://github.com/emberobserver/client/blob/master/icomoon-font/selection.json on icomoon (https://icomoon.io/app/#/select) would allow generating svgs in place of the current font.

**Comment by kaermorchen** [comment]
I am not sure that icomoon is a best choice. Materialdesignicons has similar icons and a lot of more. For materialdesignicons we have ember addon which can create small svg file which have just using icons and no needs any external service. This is more conveniently for other developers.

**Comment by kategengler** [comment]
We're _already_ using icomoon, just need to switch to svgs. The external service is free.

**Comment by kategengler** [comment]
Moved to using svg icons using icomoon

**Pull request closed without merging**
