### PR TITLE
Add intra page links

### PR DESCRIPTION
**Pull request by shankarsridhar**
@kategengler 
Addresses https://github.com/emberobserver/client/issues/148

### CODE REVIEW

**Comment by shankarsridhar** [comment]
I added links which obviously creates a visual diff. And percy test is complaining about it.
Is there a way to make percy happy regarding this?

**Comment by kategengler** [comment]
@shankarsridhar Sorry, it is a manual approval step just for that purpose -- to see & approve visual changes.

**Comment by kategengler** [comment]
@shankarsridhar This looks great, thanks! When we pulled it down to try, we found that opening a new link (for example: <url>/addons/ember-try#categories) does not link to this section. 

It's possible this html feature isn't compatible with Ember (I've never tried to do it in an Ember app before!)

**Comment by shankarsridhar** [comment]
ah I see. Yeah, you are right. bummer. it works only when the links are clicked after the page is loaded. But, opening the intra page link in a new tab does not work; and it seems like it is a problem with ember apps. 

I am open to suggestions; meanwhile, I'll take a look at https://github.com/mike-north/ember-anchor and see if that would help with this problem.

**Pull request closed without merging**
